### ISSUE TITLE
Importing linalg yields sh1: syntax error missing "}"

### ISSUE THREAD

**Issue by DomagojHack** [lebedov/scikit-cuda#193] opened 2017-04-05 09:34 UTC
when I try to do 
`import skcuda.linalg as linalg`

console is yielding this error:
`sh: 1: Syntax error: Missing "}" `

`linalg.init() ` works though

Linalg routines seems to work fine but it is not pleasant to see this error every time I run my code. So any ideas why am I getting this error?

**Comment by lebedov** [comment] 2017-04-05 10:56
I can't reproduce this error with the latest revision on GitHub.

**Comment by DomagojHack** [comment] 2017-04-05 11:03
I've tried to reinstall but the error keeps coming up. Probably my system fault. Gonna poke around ...

**Comment by lebedov** [comment] 2017-05-24 04:17
Closing - feel free to open if this is still an issue with the latest revision on GitHub.

**Closed by lebedov** 2017-05-24 04:17 UTC

**Comment by nerfsmurf** [comment] 2017-09-22 01:20
I'm having this issue also, using the latest from Github
